####   Display   ###############################

# Include more detail for troubleshoot
verbose = "info"

# Do not show progress bar in GH Action
progress = false

####   Requests   ###############################

# Have a bigger timeout due to some sites being slow sometimes
timeout = 65

# Retry failed links after 5 seconds to avoid some local throttling situations
retry_wait_time = 5

# Tolerate HTTP 403 Forbidden responses because it's a common response for domains behind Cloudflare.
accept = [403]

# Tolerate certificate issues since several sites have certificate chain issues :(
insecure = true

####   Exclusions   ###############################

# Safeguard so avoid GH Action accessing runner local endpoints


# Ignore email links
exclude_mail = false

exclude_file = ".github/workflows/lycheeignore"
exclude_file = [ ".github/workflows/.lycheeignore" ]
