name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
  schedule:
    - cron: '55 5 * * *'

jobs:
  val-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install lychee
      - name: Validate links
        uses: lycheeverse/lychee-action@v1.8.0
        id: lychee-validation
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: --config .github/workflows/lychee.toml README.md
          fail: true
          format: markdown
          jobsummary: true
          output: lychee/out.md
      - name: Handle Errors
        run: |
          # Add error handling logic here
          exit_code=$?
          if [ $exit_code -eq 2 ]; then
            echo 'Error: Exit code 2'
            # Add actions to handle this error
          elif [ $exit_code -eq 1 ]; then
            echo 'Error: Exit code 1'
            # Add actions to handle this error
          else
            echo 'No errors'
          fi
        if: steps.lychee-validation.outcome == 'failure'
