name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
  schedule:
    - cron: '55 5 * * *'

jobs:
  val-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install lychee
      - name: Validate links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: --config .github/workflows/lychee.toml README.md
          fail: true
          format: markdown
          jobsummary: true
          output: lychee/out.md
